services:
  - type: web
    name: youtube-proxy-deploy
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: YTDLP_NO_UPDATE
        value: "1"
